apiVersion: v1
kind: Pod
metadata:
  name: emptydirvolume
  labels:
    environment: staging
    tier: frontend
  namespace: test-nginx-app
spec:
  # initContainers:
  #   - name: clone-repo
  #     image: alpine/git
  #     command:
  #       - git
  #       - clone
  #       # - --progress
  #       - https://github.com/SaumyaBhushan/http-page.git
  #       - /usr/share/nginx/html
  #     volumeMounts:
  #       - name: webb
  #         mountPath: "/usr/share/nginx/html"
  containers:
    - name: nginx
      image: nginx
      ports:
        - name: http
          containerPort: 80
      volumeMounts:
        - name: webb
          mountPath: "/usr/share/nginx/html"
  volumes:
    - name: webb
      emptyDir: {}