apiVersion: v1
kind: Service
metadata:
  name:  nginx-service
spec:
  selector:
    app:  Selector Label
  type:  ClusterIP
  ports:
  - name:  http
    protocol: TCP
    port:  80
    targetPort:  8080