apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-app
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      name: no123
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.16-perl
          ports:
            - containerPort: 8080
