apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-rolling-update
  namespace: nginx-app
  labels:
    app: nginx-rolling-update
spec:
  selector:
    matchLabels:
      app: nginx-rolling-update
  replicas: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
  template:
    metadata:
      name: nginx
      labels:
        app: nginx-rolling-update
    spec:
      containers:
        - name: nginx
          image: nginx:1.16-perl
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
