apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-recreate
  namespace: nginx-app
  labels:
    app: nginx-recreate
  annotations:
    description: "nginx deployment with recrete strategy"
spec:
  selector:
    matchLabels:
      app: nginx-recreate
  replicas: 4
  strategy:
    type: Recreate
  template:
    metadata:
      name: nginx
      labels:
        app: nginx-recreate
    spec:
      containers:
        - name: nginx
          image: nginx:1.16-perl
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"

    