apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: nginx-app
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.16-perl
      ports:
        - containerPort: 8080
