---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: web
spec:
  containers:
    - name: ubuntu
      image: busybox
      command: ["/bin/sh"]
      args: ["-c", "echo Inside busybox"]
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
